// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package orders

import ()

type Order struct {
	ID               int32  `json:"id"`
	RecipientName    string `json:"recipient_name"`
	RecipientAddress string `json:"recipient_address"`
	Shipper          string `json:"shipper"`
}
