// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package outbounds

import ()

type Outbound struct {
	ID      int32 `json:"id"`
	ItemID  int32 `json:"item_id"`
	OrderID int32 `json:"order_id"`
	Qty     int32 `json:"qty"`
}
